### ISSUE TITLE
Is there a plan to support Windows?

### ISSUE THREAD

**Issue by tony2u** [liltom-eth/llama2-webui#31]
Since openai/triton still not worked on windows yet, and with torch.compile heavily relying on triton.

Traceback (most recent call last):
  File "E:\Projects\GPT\llama2-webui\app.py", line 62, in <module>
    llama2_wrapper.init_model()
  File "E:\Projects\GPT\llama2-webui\llama2_wrapper\model.py", line 13, in init_model
    self.model = LLAMA2_WRAPPER.create_llama2_model(
  File "E:\Projects\GPT\llama2-webui\llama2_wrapper\model.py", line 52, in create_llama2_model
    model = AutoModelForCausalLM.from_pretrained(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\models\auto\auto_f
actory.py", line 492, in from_pretrained
    model_class = _get_model_class(config, cls._model_mapping)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\models\auto\auto_f
actory.py", line 376, in _get_model_class
    supported_models = model_mapping[type(config)]
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\models\auto\auto_f
actory.py", line 666, in __getitem__
    return self._load_attr_from_module(model_type, model_name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\models\auto\auto_f
actory.py", line 680, in _load_attr_from_module
    return getattribute_from_module(self._modules[module_name], attr)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\models\auto\auto_f
actory.py", line 625, in getattribute_from_module
    if hasattr(module, attr):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\utils\import_utils
.py", line 1089, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\utils\import_utils
.py", line 1101, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.llama.modeling_llama because of the following error (look up to see i
ts traceback):
DLL load failed while importing libtriton: The specified module could not be found.

**Comment by liltom-eth** [comment]
@tony2u I believe llama.cpp models work on Windows, and I am using `WSL2` for transformer backend models.
