### ISSUE TITLE
ERROR. How to fix ?

### ISSUE THREAD

**Issue by oaefou** [liltom-eth/llama2-webui#67]
Running on backend llama.cpp.
Model path is empty.
Use default llama.cpp model path: ./models/llama-2-7b-chat.ggmlv3.q4_0.bin
Model exists in ./models/llama-2-7b-chat.ggmlv3.q4_0.bin.
Traceback (most recent call last):
  File "C:\llama2-webui\app.py", line 325, in <module>
    main()
  File "C:\llama2-webui\app.py", line 56, in main
    llama2_wrapper = LLAMA2_WRAPPER(
                     ^^^^^^^^^^^^^^^
  File "C:\llama2-webui\llama2_wrapper\model.py", line 99, in __init__
    self.init_model()
  File "C:\llama2-webui\llama2_wrapper\model.py", line 103, in init_model
    self.model = LLAMA2_WRAPPER.create_llama2_model(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\llama2-webui\llama2_wrapper\model.py", line 125, in create_llama2_model
    model = Llama(
            ^^^^^^
  File "C:\Python311\Lib\site-packages\llama_cpp\llama.py", line 323, in __init__
    assert self.model is not None
AssertionError

**Comment by shiloa** [comment]
Try running `pip install -r requirements.txt` in the llama2-webui root, that fixed it for me.

**Comment by jamartinh** [comment]
Thanks, but for me still does not work

**Comment by liltom-eth** [comment]
@oaefou @shiloa  hi now the new release llama2-wrapper=0.1.13 will lock on llama-cpp-python = "0.1.77" to support old ggml models.
New release will support gguf models.

**Comment by liltom-eth** [comment]
https://github.com/liltom-eth/llama2-webui/pull/73 now supporting gguf models.
