### ISSUE TITLE
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge

### ISSUE THREAD

**Issue by HougeLangley** [liltom-eth/llama2-webui#80]
Running `python app.py`

```
(llama2-webui) [09:10:56] houge (llama2-webui) ~/llama2-webui [main ●1…4]
$ python app.py                   
Running on GPU with backend torch transformers.
Loading checkpoint shards:   0%|                         | 0/2 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/houge/llama2-webui/app.py", line 418, in <module>
    main()
  File "/home/houge/llama2-webui/app.py", line 60, in main
    llama2_wrapper = LLAMA2_WRAPPER(
                     ^^^^^^^^^^^^^^^
  File "/home/houge/llama2-webui/llama2_wrapper/model.py", line 99, in __init__
    self.init_model()
  File "/home/houge/llama2-webui/llama2_wrapper/model.py", line 103, in init_model
    self.model = LLAMA2_WRAPPER.create_llama2_model(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/houge/llama2-webui/llama2_wrapper/model.py", line 146, in create_llama2_model
    model = AutoModelForCausalLM.from_pretrained(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/houge/llama2-webui/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 493, in from_pretrained
    return model_class.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/houge/llama2-webui/lib/python3.11/site-packages/transformers/modeling_utils.py", line 2903, in from_pretrained
    ) = cls._load_pretrained_model(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/houge/llama2-webui/lib/python3.11/site-packages/transformers/modeling_utils.py", line 3246, in _load_pretrained_model
    state_dict = load_state_dict(shard_file)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/houge/llama2-webui/lib/python3.11/site-packages/transformers/modeling_utils.py", line 447, in load_state_dict
    with safe_open(checkpoint_file, framework="pt") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge
[09:11:31] [cost 9.708s] python app.py
```

**Comment by HougeLangley** [comment]
![image](https://github.com/liltom-eth/llama2-webui/assets/1161594/e8846ca5-9da0-452a-800e-61e0503fe9fa)

**Comment by HougeLangley** [comment]
![image](https://github.com/liltom-eth/llama2-webui/assets/1161594/eef612e0-72d0-4687-b26e-1661a41b9f7f)

**Comment by HougeLangley** [comment]
Sorry for my module file, re-download will be fine.
